package blobs_test

import (
	"bytes"
	"context"
	"errors"
	"io"
	"os"
	"path/filepath"
	"testing"

	"github.com/Saieshwar5/cuckoo/server/internal/blobs"
)

func read(t *testing.T, store blobs.Store, key string) string {
	t.Helper()
	rc, err := store.Open(context.Background(), key)
	if err != nil {
		t.Fatalf("Open(%q): %v", key, err)
	}
	defer func() { _ = rc.Close() }()
	data, err := io.ReadAll(rc)
	if err != nil {
		t.Fatalf("read %q: %v", key, err)
	}
	return string(data)
}

func TestDiskRoundTrip(t *testing.T) {
	ctx := context.Background()
	store, err := blobs.NewDisk(filepath.Join(t.TempDir(), "media"))
	if err != nil {
		t.Fatalf("NewDisk: %v", err)
	}

	if err := store.Put(ctx, "ab/cd/abcd", bytes.NewReader([]byte("hello"))); err != nil {
		t.Fatalf("Put: %v", err)
	}
	if got := read(t, store, "ab/cd/abcd"); got != "hello" {
		t.Errorf("read back %q", got)
	}

	// Writing again replaces, so a retry of an upload is not two files.
	if err := store.Put(ctx, "ab/cd/abcd", bytes.NewReader([]byte("again"))); err != nil {
		t.Fatalf("Put again: %v", err)
	}
	if got := read(t, store, "ab/cd/abcd"); got != "again" {
		t.Errorf("after replace %q", got)
	}

	if err := store.Delete(ctx, "ab/cd/abcd"); err != nil {
		t.Fatalf("Delete: %v", err)
	}
	if _, err := store.Open(ctx, "ab/cd/abcd"); !errors.Is(err, blobs.ErrNotFound) {
		t.Errorf("after delete, Open = %v, want ErrNotFound", err)
	}
	// Deleting what is already gone is what the caller asked for.
	if err := store.Delete(ctx, "ab/cd/abcd"); err != nil {
		t.Errorf("second Delete: %v", err)
	}
}

// A failed write leaves nothing behind, so no key ever names half a file.
func TestDiskLeavesNothingWhenAWriteFails(t *testing.T) {
	ctx := context.Background()
	root := t.TempDir()
	store, err := blobs.NewDisk(root)
	if err != nil {
		t.Fatalf("NewDisk: %v", err)
	}

	broken := io.MultiReader(bytes.NewReader([]byte("start")), errReader{})
	if err := store.Put(ctx, "ab/cd/abcd", broken); err == nil {
		t.Fatal("Put succeeded on a reader that failed")
	}
	if _, err := store.Open(ctx, "ab/cd/abcd"); !errors.Is(err, blobs.ErrNotFound) {
		t.Errorf("a partial file was left at the key: %v", err)
	}
	entries, err := os.ReadDir(filepath.Join(root, "ab", "cd"))
	if err != nil {
		t.Fatalf("read directory: %v", err)
	}
	if len(entries) != 0 {
		t.Errorf("temporary files left behind: %v", entries)
	}
}

// Keys are generated by this server, but a key that escaped the root would
// be the filesystem readable over HTTP.
func TestDiskRefusesKeysThatEscape(t *testing.T) {
	ctx := context.Background()
	root := t.TempDir()
	store, err := blobs.NewDisk(filepath.Join(root, "media"))
	if err != nil {
		t.Fatalf("NewDisk: %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, "secret"), []byte("shh"), 0o600); err != nil {
		t.Fatalf("write neighbour file: %v", err)
	}

	for _, key := range []string{
		"", "/etc/passwd", "../secret", "ab/../../secret", "ab/cd/..", ".", "ab//cd",
		"ab/cd/ef\x00gh", `ab\cd`, "ab/cd/eé",
	} {
		if _, err := store.Open(ctx, key); err == nil {
			t.Errorf("Open(%q) was allowed", key)
		}
		if err := store.Put(ctx, key, bytes.NewReader([]byte("x"))); err == nil {
			t.Errorf("Put(%q) was allowed", key)
		}
		if err := store.Delete(ctx, key); err == nil {
			t.Errorf("Delete(%q) was allowed", key)
		}
	}
}

type errReader struct{}

func (errReader) Read([]byte) (int, error) { return 0, errors.New("network died") }
